# Generated by Django 3.2 on 2024-09-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20240916_0932'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.ForeignKey(default=1, help_text='Выбрать из имеющегося персонала', on_delete=django.db.models.deletion.CASCADE, to='company.personalmodel', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
