# Generated by Django 3.2 on 2024-09-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='subtitle',
            field=models.CharField(help_text='Не больше 70 символов, обязательно к заполнению, используется для поисковой индексации', max_length=170, null=True, verbose_name='Подзаголовок статьи'),
        ),
    ]
