# Generated by Django 3.2 on 2024-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='note',
            field=models.TextField(blank=True, help_text='Для разбивки на параграфы используется одинарный перенос (Не обязательно)', null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='text',
            field=models.TextField(help_text='Полный текст статьи. Для разбивки на параграфы используется одинарный перенос', verbose_name='Текст статьи'),
        ),
    ]
