# Generated by Django 3.2 on 2024-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240916_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='img_note',
            field=models.ImageField(default=1, help_text='Красивое фото', upload_to='blog/', verbose_name='Дополнительная фотография'),
            preserve_default=False,
        ),
    ]
