# Generated by Django 3.2 on 2024-09-16 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SertificatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='На русском языке, не больше 100 символов', max_length=100, verbose_name='Название сертификата')),
                ('year', models.IntegerField(help_text='в формате ГГГГ', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выдачи')),
                ('company', models.CharField(help_text='На русском языке, не больше 100 символов', max_length=100, verbose_name='Компания которая выдала сертификат')),
                ('image', models.ImageField(help_text='Портретное фото', upload_to='company/sertificates', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Дипломы и сертификаты персонала',
            },
        ),
        migrations.AlterModelOptions(
            name='personalmodel',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Персонал компании'},
        ),
    ]
