# Generated by Django 3.2 on 2024-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название', max_length=100, verbose_name='Не больше 100 символов')),
                ('subtitle', models.CharField(help_text='Подзаголовок', max_length=300, verbose_name='Краткое описание услуги, не больше 300 символов')),
                ('price_min', models.FloatField(blank=True, default=0.0, help_text='Стоимость от. Не обязательно к заполнению', null=True, verbose_name='Цена от')),
                ('price_max', models.FloatField(blank=True, default=0.0, help_text='Стоимость до. Не обязательно к заполнению', null=True, verbose_name='Цена до')),
                ('description', models.TextField(help_text='Подробное описание услуги', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', upload_to='catalog/services/', verbose_name='Обложка')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Услуги компании',
                'verbose_name_plural': 'Услуги предоставляемые компанией',
            },
        ),
    ]
