# Generated by Django 3.2 on 2024-09-12 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не больше 70 символов', max_length=70, verbose_name='Заголовок')),
                ('description', models.CharField(help_text='Не больше 100 символов', max_length=100, verbose_name='Краткое описание')),
                ('conditions', models.CharField(help_text='Не больше 100 символов', max_length=100, null=True, verbose_name='Спецпредложение')),
                ('percent', models.FloatField(blank=True, default=0.0, help_text='Если подразумевается скидка', null=True, verbose_name='Процент')),
                ('date_of', models.DateField(default=django.utils.timezone.now, help_text='Дата начала акции', verbose_name='Дата')),
                ('date_to', models.DateField(default=django.utils.timezone.now, help_text='Дата окончания акции', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Спецпредложения',
                'verbose_name_plural': 'Скидки и акции',
            },
        ),
    ]
