# Generated by Django 3.2 on 2024-09-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20240906_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'verbose_name': 'Услуги компании', 'verbose_name_plural': 'Услуги предоставляемые компанией'},
        ),
    ]
