# Generated by Django 3.2 on 2024-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_discountmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountmodel',
            options={'verbose_name': 'Спецпредложение', 'verbose_name_plural': 'Скидки и акции'},
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
