# Generated by Django 3.2 on 2024-09-13 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20240912_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='date_of',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата начала акции', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата окончания акции', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='percent',
            field=models.IntegerField(blank=True, help_text='Если подразумевается скидка', null=True, verbose_name='Процент'),
        ),
    ]
