# Generated by Django 3.2 on 2024-09-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20240913_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='price_min',
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='adouts',
            field=models.CharField(default=1, help_text='Название', max_length=100, verbose_name='Не больше 100 символов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='includes',
            field=models.CharField(default=1, help_text='Название', max_length=100, verbose_name='Не больше 100 символов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='methodology',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
