# Generated by Django 3.2 on 2024-09-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20240930_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopelementmodel',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='shopelementmodel',
            name='depth',
            field=models.FloatField(blank=True, help_text='Для чаши бассейна, если другая категория то не заполнять!', null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='shopelementmodel',
            name='length',
            field=models.FloatField(blank=True, help_text='Для чаши бассейна, если другая категория то не заполнять!', null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='shopelementmodel',
            name='width',
            field=models.FloatField(blank=True, help_text='Для чаши бассейна, если другая категория то не заполнять!', null=True, verbose_name='Ширина'),
        ),
    ]
