# Generated by Django 3.2 on 2024-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20240930_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopelementmodel',
            name='depth',
            field=models.FloatField(blank=True, default=0.0, help_text='Для чаши бассейна, если другая категория то не заполнять!', null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='shopelementmodel',
            name='length',
            field=models.FloatField(blank=True, default=0.0, help_text='Для чаши бассейна, если другая категория то не заполнять!', null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='shopelementmodel',
            name='width',
            field=models.FloatField(blank=True, default=0.0, help_text='Для чаши бассейна, если другая категория то не заполнять!', null=True, verbose_name='Ширина'),
        ),
    ]
