# Generated by Django 3.2 on 2024-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopelementmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='shopelementmodel',
            name='image',
            field=models.ManyToManyField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', related_name='product', to='catalog.Photo', verbose_name='Фото товара'),
        ),
    ]
