# Generated by Django 3.2 on 2024-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPageAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='не больше 100 символов, включая пробелы и знаки припенания', max_length=100, verbose_name='Заголовок пункта "О нас"')),
                ('subtitle', models.CharField(help_text='не больше 50, включая пробелы и знаки припенания, распалагается под иконкой в блоке', max_length=50, verbose_name='Заголовок иконки')),
                ('description', models.CharField(help_text='не больше 500, включая пробелы и знаки припенания', max_length=500, verbose_name='Описание блока "О нас"')),
                ('icon', models.ImageField(help_text='Использовать без фона', upload_to='content/icons', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Контент блока "о нас"',
                'verbose_name_plural': 'Управление блоком "о нас"',
            },
        ),
        migrations.CreateModel(
            name='FirstPageAwesomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='не больше 100 символов, включая пробелы и знаки припенания', max_length=100, verbose_name='Заголовок пункта "приемущества"')),
                ('text', models.CharField(help_text='не больше 300, включая пробелы и знаки припенания', max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контент блока "Наши приемущества"',
                'verbose_name_plural': 'Управление блоком "Наши приемущества"',
            },
        ),
        migrations.CreateModel(
            name='FirstPageTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(help_text='не больше 100 символов, включая пробелы и знаки припенания', max_length=100, verbose_name='Приветственный текст вверху заголовка')),
                ('title', models.CharField(help_text='не больше 200 символов, включая пробелы и знаки припенания', max_length=200, verbose_name='Заголовок первой страницы')),
                ('subtitle', models.CharField(help_text='не больше 500, включая пробелы и знаки припенания', max_length=500, verbose_name='Подзаголовок первой страницы')),
            ],
            options={
                'verbose_name': 'Контент первой страницы',
                'verbose_name_plural': 'Управление баннером (информация первого экрана)',
            },
        ),
    ]
