# Generated by Django 3.2 on 2024-09-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(help_text='не больше 100 символов, включая пробелы и знаки припенания', max_length=100, verbose_name='Приветственный текст вверху заголовка')),
                ('title', models.CharField(help_text='не больше 200 символов, включая пробелы и знаки припенания', max_length=200, verbose_name='Заголовок первой страницы')),
                ('subtitle', models.CharField(help_text='не больше 500, включая пробелы и знаки припенания', max_length=500, verbose_name='Подзаголовок первой страницы')),
            ],
        ),
    ]
