# Generated by Django 3.2 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutValuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='не больше 100 символов, включая пробелы и знаки припенания', max_length=100, verbose_name='Заголовок пункта "О нас"')),
                ('description', models.CharField(help_text='не больше 500, включая пробелы и знаки припенания', max_length=300, verbose_name='Описание блока "О нас"')),
                ('icon', models.ImageField(help_text='Использовать без фона', upload_to='content/icons/values', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности компании( отображается на странице "О нас")',
            },
        ),
    ]
