# Generated by Django 3.2 on 2024-09-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20240905_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstpagetitlemodel',
            options={'verbose_name': 'Контент первой страницы', 'verbose_name_plural': 'Управление заголовками первой страницы'},
        ),
    ]
