# Generated by Django 3.2 on 2024-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_firstpagetitlemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPageAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='не больше 200 символов, включая пробелы и знаки припенания', max_length=200, verbose_name='Заголовок первой страницы')),
                ('subtitle', models.CharField(help_text='не больше 500, включая пробелы и знаки припенания', max_length=500, verbose_name='Подзаголовок первой страницы')),
            ],
            options={
                'verbose_name': 'Контент блока "о нас"',
                'verbose_name_plural': 'Управление блоком "о нас',
            },
        ),
        migrations.AlterModelOptions(
            name='firstpagetitlemodel',
            options={'verbose_name': 'Контент первой страницы', 'verbose_name_plural': 'Управление баннером (информация первого экрана)'},
        ),
    ]
