# Generated by Django 3.2 on 2024-09-06 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20240906_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpageaboutmodel',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, help_text='не больше 500, включая пробелы и знаки припенания', max_length=500, verbose_name='Подзаголовок блока "О нас"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firstpageaboutmodel',
            name='subtitle',
            field=models.CharField(help_text='не больше 50, включая пробелы и знаки припенания, расолагается под иконкой в блоке', max_length=50, verbose_name='Краткое описание "О нас"'),
        ),
    ]
