# Generated by Django 3.2 on 2024-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20240906_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpageaboutmodel',
            name='description',
            field=models.CharField(help_text='не больше 500, включая пробелы и знаки припенания', max_length=500, verbose_name='Описание блока "О нас"'),
        ),
        migrations.AlterField(
            model_name='firstpageaboutmodel',
            name='subtitle',
            field=models.CharField(help_text='не больше 50, включая пробелы и знаки припенания, распалагается под иконкой в блоке', max_length=50, verbose_name='Заголовок иконки'),
        ),
    ]
