# Generated by Django 3.2 on 2024-09-12 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО с согласия клиента', max_length=200, verbose_name='Имя клиента')),
                ('text', models.CharField(help_text='Со слов клиента, не болшьше 1000 символов', max_length=100, verbose_name='Текст отзыва')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=False, help_text='Добавляет отзыв на сайт', verbose_name='Опубликовано')),
                ('image', models.ImageField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', upload_to='review/', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
    ]
