# Generated by Django 3.2 on 2024-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewmodel_sity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='image',
            field=models.ImageField(help_text='Фото объекта', upload_to='review/', verbose_name='Фото объекта'),
        ),
    ]
